### ISSUE TITLE
python binding is broken

### ISSUE THREAD

**Issue by sphaero** [zeromq/czmq#1327]
```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from czmq import *
  File "/home/arnaud/src/czmq/bindings/python/czmq.py", line 3312, in <module>
    lib.zlistx_set_destructor.argtypes = [zlistx_p, czmq_destructor]
NameError: name 'czmq_destructor' is not defined
```
I think this is actualy a problem of the generator (zproject)

I patched it manually like this
```
diff --git a/bindings/python/czmq.py b/bindings/python/czmq.py
index f81576d..004e61b 100644
--- a/bindings/python/czmq.py
+++ b/bindings/python/czmq.py
@@ -3258,6 +3258,11 @@ Returns the item, or NULL if there is no such item.
 
 
 # zlistx
+##### MISSING DEFS
+zlistx_destructor_fn = CFUNCTYPE(None, POINTER(c_void_p))
+zlistx_duplicator_fn = CFUNCTYPE(c_void_p, c_void_p)
+zlistx_comparator_fn = CFUNCTYPE(c_int, c_void_p, c_void_p)
+##### eND
 lib.zlistx_new.restype = zlistx_p
 lib.zlistx_new.argtypes = []
 lib.zlistx_destroy.restype = None
@@ -3309,11 +3314,11 @@ lib.zlistx_reorder.argtypes = [zlistx_p, c_void_p, c_bool]
 lib.zlistx_dup.restype = zlistx_p
 lib.zlistx_dup.argtypes = [zlistx_p]
 lib.zlistx_set_destructor.restype = None
-lib.zlistx_set_destructor.argtypes = [zlistx_p, czmq_destructor]
+lib.zlistx_set_destructor.argtypes = [zlistx_p, zlistx_destructor_fn]
 lib.zlistx_set_duplicator.restype = None
-lib.zlistx_set_duplicator.argtypes = [zlistx_p, czmq_duplicator]
+lib.zlistx_set_duplicator.argtypes = [zlistx_p, zlistx_duplicator_fn]
 lib.zlistx_set_comparator.restype = None
-lib.zlistx_set_comparator.argtypes = [zlistx_p, czmq_comparator]
+lib.zlistx_set_comparator.argtypes = [zlistx_p, zlistx_comparator_fn]
 lib.zlistx_test.restype = None
 lib.zlistx_test.argtypes = [c_bool]
```
There is a problem in test.py as well
```
$ python test.py 
........E.
======================================================================
ERROR: test_zmsg (__main__.TestCZMQ)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 708, in test_zmsg
    buffer_size = msg.encode(buffer)
  File "/home/arnaud/src/czmq/bindings/python/czmq.py", line 4117, in encode
    return lib.zmsg_encode(self._as_parameter_, byref(c_void_p.from_param(buffer)))
ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected LP_c_void_p instance instead of pointer to LP_c_byte

----------------------------------------------------------------------
Ran 10 tests in 2.453s

FAILED (errors=1)
E: 16-01-27 18:45:42 dangling sockets: cannot terminate ZMQ safely
```
quick fix:
```
diff --git a/bindings/python/test.py b/bindings/python/test.py
index 25f52b9..ab47866 100644
--- a/bindings/python/test.py
+++ b/bindings/python/test.py
@@ -704,7 +704,7 @@ class TestCZMQ(unittest.TestCase):
         self.assertEqual(msg.addmem(blank, 65537), 0)
         del blank
         self.assertEqual(msg.size(), 9)
-        buffer = POINTER(c_byte)()
+        buffer = c_void_p()
         buffer_size = msg.encode(buffer)
         del msg
         msg = Zmsg.decode(buffer, buffer_size)
```
not sure if it's correct though

more hacking tomorrow :)

**Comment by sphaero** [comment]
fixed during the hackaton :)
