### ISSUE TITLE
Curve Server : Assertion failure during processing of INITIATE command

### ISSUE THREAD

**Issue by vtambve** [zeromq/czmq#1470]
Here I have a modified version of the Ironhouse pattern example as mentioned in Peter's blog post about ZeroMQ Security http://hintjens.com/blog:49. The modifications I made are as follows :
1. Split the client and server into separate executables
2. Client does a 'bind' and the server does a 'connect'
3. Both client and server communicate over multiple messages with 2 second delays between them.

client.c

```
#include <czmq.h>

int main (void) 
{
    //  Create context
    zctx_t *ctx = zctx_new ();

    zcert_t *client_cert = zcert_load (".client/clientcert.sec");
    zcert_t *server_cert = zcert_load (".client/servercert.txt");
    char *server_key = zcert_public_txt (server_cert);

    //  Create and bind client socket
    void *client = zsocket_new (ctx, ZMQ_PULL);
    zcert_apply (client_cert, client);
    zsocket_set_curve_serverkey (client, server_key);
    zsocket_bind (client, "tcp://*:9000");

    //  Send a single message from server to client
    for(int i=0; i<30; i++) {
        char *message = zstr_recv (client);
        assert (streq (message, "Hello"));
        free (message);
        printf("Ironhouse iteration %d OK\n", i+1);
        sleep(2);
    }

    zcert_destroy (&client_cert);
    zcert_destroy (&server_cert);
    zctx_destroy (&ctx);
    return 0;
}

```

server.c

```
#include <czmq.h>

int main (void) 
{
    //  Create context and start authentication engine
    zctx_t *ctx = zctx_new ();
    zauth_t *auth = zauth_new (ctx);
    zauth_set_verbose (auth, true);
    zauth_allow (auth, "127.0.0.1");

    //  Tell authenticator to use the certificate stored in '.server' folder
    zauth_configure_curve (auth, "*", ".server");


    // Read the server certificate from the .server folder
    zcert_t *server_cert = zcert_load (".server/servercert.sec");

    // Create and connect server socket
    void *server = zsocket_new (ctx, ZMQ_PUSH);
    zcert_apply (server_cert, server);
    zsocket_set_curve_server (server, 1);
    zsocket_connect (server, "tcp://127.0.0.1:9000");

    for(int i=0; i<30; i++) {
        zstr_send (server, "Hello");
        printf ("Sent message %d \n", i+1);
        sleep(2);
    }

    zcert_destroy (&server_cert);
    zauth_destroy (&auth);
    zctx_destroy (&ctx);
    return 0;
}

```

During execution if I kill the client abruptly, and then bring it back up again, I get an assertion failure on the server end. The abort happens only after client comes up again and binds to the socket. The server aborts with an assertion from the socket while processing the INITIATE command. Here is the  stack trace for the assertion :

client.task

```
Assertion failed: zap_pipe == NULL (src/session_base.cpp:301)

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff5e72700 (LWP 17716)]
0x00007ffff6acd5d7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-78.el7.x86_64 libgcc-4.8.3-9.el7.x86_64 libstdc++-4.8.3-9.el7.x86_64
(gdb) bt
#0  0x00007ffff6acd5d7 in raise () from /lib64/libc.so.6
#1  0x00007ffff6acecc8 in abort () from /lib64/libc.so.6
#2  0x00007ffff7696b99 in zmq::zmq_abort (errmsg_=errmsg_@entry=0x7ffff76c7e51 "zap_pipe == NULL") at src/err.cpp:84
#3  0x00007ffff76adce3 in zmq::session_base_t::zap_connect (this=0x611d50) at src/session_base.cpp:301
#4  0x00007ffff7695194 in zmq::curve_server_t::process_initiate (this=0x7fffe80052f0, msg_=msg_@entry=0x7fffe8000908)
    at src/curve_server.cpp:500
#5  0x00007ffff76953b1 in zmq::curve_server_t::process_handshake_command (this=<optimized out>, msg_=0x7fffe8000908)
    at src/curve_server.cpp:113
#6  0x00007ffff76ba741 in zmq::stream_engine_t::process_handshake_command (this=0x7fffe8000e60, msg_=0x7fffe8000908)
    at src/stream_engine.cpp:761
#7  0x00007ffff76b92f3 in zmq::stream_engine_t::in_event (this=0x7fffe8000e60) at src/stream_engine.cpp:323
#8  0x00007ffff769681e in zmq::epoll_t::loop (this=0x605bb0) at src/epoll.cpp:176
#9  0x00007ffff76bfec0 in thread_routine (arg_=0x605c30) at src/thread.cpp:96
#10 0x00007ffff667bdf5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007ffff6b8e1ad in clone () from /lib64/libc.so.6
(gdb)
```

Please note that this issue does not happen when the client does a 'connect' and server, a 'bind'.

Complete debugger output for both client and server has been attached along with certificates used for execution.

[client-stack-trace.txt](https://github.com/zeromq/czmq/files/335726/client-stack-trace.txt)
[server-stack-trace.txt](https://github.com/zeromq/czmq/files/335727/server-stack-trace.txt)
[certificates.tar.gz](https://github.com/zeromq/czmq/files/335860/certificates.tar.gz)

**Comment by zausiu** [comment]
Hello, I have encountered a similar issue ~ I want to known have you find the solution ?

**Comment by GerardGarcia** [comment]
I have the same problem in a PUB-SUB pattern where the server connects to the client.

**Comment by kumarsm** [comment]
Same issue found in the same condition as mentioned by GerardGarcia.  Would like to know if a fix is available.

**Comment by bluca** [comment]
Closing as this is a libzmq issue: https://github.com/zeromq/libzmq/issues/2608
This should fix it: https://github.com/zeromq/libzmq/issues/2608
