### ISSUE TITLE
zsys access from python

### ISSUE THREAD

**Issue by diorcety** [zeromq/czmq#1684]
There is no way to access zsys_* functions from python binding

**Comment by bluca** [comment]
Yes that is a known problem, since they are not generated by zproject there's no binding generation. No idea how we can solve it.

**Comment by diorcety** [comment]
This trigger an issue on Windows. Either a crash or a stall (after last python code)

zsys_shutdown is called atexit.
But something is done before atexit by python internal code (WSACleanup?)
This lead to this issue: https://lists.zeromq.org/pipermail/zeromq-dev/2016-March/030059.html

if i call 
    import ctypes
    lib = ctypes.cdll.LoadLibrary('libczmq')
    lib.zsys_shutdown.restype = None
    lib.zsys_shutdown.argtypes = []
    lib.zsys_shutdown()
at the end of my python program, i have no issue at all...

**Comment by bluca** [comment]
I thought there was no atexit on windows?

**Comment by bluca** [comment]
That was with a DLL build though, might not be your case:
https://github.com/zeromq/czmq/pull/1608
https://github.com/zeromq/zproject/pull/836

**Comment by jemc** [comment]
> Yes that is a known problem, since they are not generated by zproject there's no binding generation. No idea how we can solve it.

Is there a deficiency in zproject or oddity about `zsys` that prevents someone writing the zproject API def for it? Since there is no `zsys` class instance, I think that just means all of the methods would be `singleton` methods, as described here:

https://github.com/zeromq/zproject/blob/dfb1af34e52350cd6a94956f618e41611c8eb152/api/myclass.api#L99

**Comment by bluca** [comment]
Honestly not sure. Perhaps it's simply that nobody has tried to convert it until now. PRs welcome as usual :-)

**Comment by jemc** [comment]
Right, I just wanted to see if there was a known deficiency in the zproject API model, since I helped design it (however many years ago).

**Comment by jemc** [comment]
So @diorcety if you wanted to try your hand at writing an API def for `zsys` to go in [this directory](https://github.com/zeromq/czmq/tree/master/api), you could generate the bindings you crave - and let us know if you get stuck and need to ask questions about how it works.

**Comment by diorcety** [comment]
I manage do create the api. but i have two issues. First one:
`(zproject_nodejs.gsl 704) Undefined expression:`
Second one: Even if I skip nodejs, python binding is not built.

**Comment by sappo** [comment]
Push your changes to your fork and I'll have a look at it.

Am 15.06.2017 09:23 schrieb "Diorcet Yann" <notifications@github.com>:

I manage do create the api. but i have two issues. First one:
(zproject_nodejs.gsl 704) Undefined expression:
Second one: Even if I skip nodejs, python binding is not built.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zeromq/czmq/issues/1684#issuecomment-308650966>, or mute
the thread

**Comment by bluca** [comment]
I found the problem: https://github.com/zeromq/zproject/pull/912

**Comment by bluca** [comment]
Now the Python test errors with:

```
Traceback (most recent call last):
  File "bindings/python/test.py", line 5, in <module>
    from czmq import *
  File "/home/lboccass/git/czmq/bindings/python/czmq/__init__.py", line 3, in <module>
    from ._czmq_ctypes import *
  File "/home/lboccass/git/czmq/bindings/python/czmq/_czmq_ctypes.py", line 7138, in <module>
    lib.zsys_udp_send.argtypes = [socket_p, zframe_p, None, c_int]
TypeError: item 3 in _argtypes_ has no from_param method
```

**Comment by diorcety** [comment]
Certainly due to inaddr_t

**Comment by bluca** [comment]
I guess we have to fix it in zproject?

**Comment by diorcety** [comment]
or remove this method from the api too

**Comment by bluca** [comment]
I guess the only problem is that the inaddr_t type is not supported - that would be worth adding

**Comment by bluca** [comment]
The problem was that the "type" was not specified together with the "c_type", so zproject's Python generation was not happy: https://github.com/zeromq/czmq/pull/1688

@sappo now the last thing to fix is JNI, any idea what this is all about:

```
:compileJava/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:384: error: <identifier> expected
    public String interface () {
                 ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:384: error: illegal start of type
    public String interface () {
                            ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:384: error: <identifier> expected
    public String interface () {
                             ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:384: error: ';' expected
    public String interface () {
                              ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:385: error: illegal start of type
        return __interface ();
        ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:393: error: class, interface, or enum expected
    native static void __setIpv6Address (String value);
                  ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:394: error: class, interface, or enum expected
    public void setIpv6Address (String value) {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:396: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:401: error: class, interface, or enum expected
    public String ipv6Address () {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:403: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:411: error: class, interface, or enum expected
    public void setIpv6McastAddress (String value) {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:413: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:419: error: class, interface, or enum expected
    public String ipv6McastAddress () {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:421: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:431: error: class, interface, or enum expected
    public void setAutoUseFd (int autoUseFd) {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:433: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:438: error: class, interface, or enum expected
    public int autoUseFd () {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:440: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:447: error: class, interface, or enum expected
    public void setLogident (String value) {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:449: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:460: error: class, interface, or enum expected
    public void setLogsender (String endpoint) {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:462: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:468: error: class, interface, or enum expected
    public void setLogsystem (boolean logsystem) {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:470: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:475: error: class, interface, or enum expected
    public void error (String format) {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:477: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:482: error: class, interface, or enum expected
    public void warning (String format) {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:484: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:489: error: class, interface, or enum expected
    public void notice (String format) {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:491: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:496: error: class, interface, or enum expected
    public void info (String format) {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:498: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:503: error: class, interface, or enum expected
    public void debug (String format) {
           ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:505: error: class, interface, or enum expected
    }
    ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:510: error: class, interface, or enum expected
    public static void test (boolean verbose) {
                  ^
/home/travis/build/bluca/czmq/bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java:512: error: class, interface, or enum expected
    }
    ^
36 errors
 FAILED
```

https://travis-ci.org/bluca/czmq/jobs/243624361

**Comment by jemc** [comment]
Seems like at least the first error is due to `interface` being a reserved word in Java.  The zproject code generator needs to obfuscate reserved words in the target language when they appear as method names

**Comment by diorcety** [comment]
Sorry I triggerd lot of issues :s

**Comment by bluca** [comment]
eheh no worries, on the contrary it's good, many issues fixed
