### ISSUE TITLE
Double free when custom zactor destructor uses bsend/brecv

### ISSUE THREAD

**Issue by vyskocilm** [zeromq/czmq#1867]
How to reproduce
```
diff --git a/src/zactor.c b/src/zactor.c
index cac3c371..0daa5c85 100644
--- a/src/zactor.c
+++ b/src/zactor.c
@@ -300,8 +300,32 @@ KTHXBAI_actor (zsock_t *pipe, void *args) {
 static void
 KTHXBAI_destructor (zactor_t *self) {
     assert (self);
-    if (zstr_send (self->pipe, "$KTHXBAI") == 0)
-        zsock_wait (self->pipe);
+    if (zstr_send (self, "$KTHXBAI") == 0)
+        zsock_wait (self);
+}
+
+static void
+BSEND_actor (zsock_t *pipe, void *args) {
+
+    zsock_signal (pipe, 0);
+    while (!zsys_interrupted) {
+        char *str = NULL;
+        void *ptr = NULL;
+        int r = zsock_brecv (pipe, "sp", &str, &ptr);
+        if (r == -1)
+            break;
+        int done = streq (str, "$TERM");
+        zstr_free (&str);
+        if (done)
+            break;
+    }
+}
+
+static void
+BSEND_destructor (zactor_t *self) {
+    assert (self);
+    if (zsock_bsend (self, "sp", "$TERM", NULL) == 0)
+        zsock_wait (self);
 }
 
 //  --------------------------------------------------------------------------
@@ -329,6 +353,13 @@ zactor_test (bool verbose)
     zactor_set_destructor (KTHXBAI, KTHXBAI_destructor);
     zactor_destroy (&KTHXBAI);
 
+    // custom destructor
+    // KTHXBAI_actor ends on "$KTHXBAI" string
+    zactor_t *BSEND = zactor_new (BSEND_actor, NULL);
+    assert (BSEND);
+    // which is the one sent by KTHXBAI_destructor
+    zactor_set_destructor (BSEND, BSEND_destructor);
+    zactor_destroy (&BSEND);
 #if defined (__WINDOWS__)
     zsys_shutdown();
 #endif
```

`zactor` selftest then ends on SIGABRT

```
Core was generated by `/home/mvyskocil/projects/zeromq/czmq/src/.libs/czmq_selftest'.                                                                                        
Program terminated with signal SIGABRT, Aborted.                                                                                                                             
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51                                                                                                    
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.                                                                                                       
[Current thread is 1 (Thread 0x7f4e833f6700 (LWP 4585))]                                                                                                                     
(gdb) bt                                                                                                                                                                     
(gdb) bt                                                                                                                                                                     
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51                                                                                                    
#1  0x00007f4e866016b1 in __GI_abort () at abort.c:79                                                                                                                        
#2  0x00007f4e86643417 in __libc_message (action=action@entry=(do_abort | do_backtrace), fmt=fmt@entry=0x7f4e8674c110 "*** Error in `%s': %s: 0x%s ***\n")                   
    at ../sysdeps/posix/libc_fatal.c:181                                                                                                                                     
#3  0x00007f4e86649b73 in malloc_printerr (action=<optimized out>, str=0x7f4e8674c498 "double free or corruption (out)", ptr=<optimized out>, ar_ptr=<optimized out>)        
    at malloc.c:5414                                                                                                                                                         
#4  0x00007f4e8664b479 in _int_free (av=0x7f4e8697ec20 <main_arena>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4163                                          
#5  0x00007f4e867304fb in tcache_thread_freeres () at malloc.c:2992                                                                                                          
#6  0x00007f4e86730552 in __libc_thread_freeres () at thread-freeres.c:29                                                                                                    
#7  0x00007f4e8698b57d in start_thread (arg=0x7f4e833f6700) at pthread_create.c:478                                                                                          
#8  0x00007f4e866c272f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by vyskocilm** [comment]
```
+        int done = streq (str, "$TERM");
+        ***zstr_free (&str);***
+        if (done)
```

was the problem, closing the issue.
