### ISSUE TITLE
Missing files from 4.2.0 zip

### ISSUE THREAD

**Issue by smac89** [zeromq/czmq#2016]
Latest release artifact does not contain most of the stuff from the `builds` directory, so when I try to build the nodejs bindings, it fails because it is missing files from there.

**Comment by sappo** [comment]
Hi @smac89, what exactly are you missing from the builds directory?

**Comment by smac89** [comment]
@sappo Basically everything. I downloaded the release zip here:
https://github.com/zeromq/czmq/releases/download/v4.2.0/czmq-4.2.0.zip

Unzip the file and check the contents of the build folder, you will see that it is missing everything but a `cmake` folder. At least I'm assuming it should contain more than that seeing as the repo has the file that this build is complaining about.

Attempting to build the node bindings by running [build.sh](https://github.com/zeromq/czmq/blob/4a3bad047544e6540998ee73b20cd79a7e871a4a/bindings/nodejs/build.sh), fails:

```sh
➜ PATH="$PWD/node_modules/.bin/:$PATH" ./build.sh 
I: checking Node.js dependencies...
I: building Node.js binding:
gyp info it worked if it ends with ok
gyp info using node-ninja@1.0.2
gyp info using node@10.15.3 | linux | x64
gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
gyp info spawn /home/chigozirim/.pyenv/shims/python2
gyp info spawn args [ '/home/chigozirim/Downloads/temp/czmq-4.2.0/bindings/nodejs/node_modules/node-ninja/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/chigozirim/Downloads/temp/czmq-4.2.0/bindings/nodejs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/chigozirim/Downloads/temp/czmq-4.2.0/bindings/nodejs/node_modules/node-ninja/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/chigozirim/.node-ninja/10.15.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/chigozirim/.node-ninja/10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/chigozirim/Downloads/temp/czmq-4.2.0/bindings/nodejs/node_modules/node-ninja',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/chigozirim/Downloads/temp/czmq-4.2.0/bindings/nodejs',
gyp info spawn args   '-Goutput_dir=/home/chigozirim/Downloads/temp/czmq-4.2.0/bindings/nodejs/build',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel' ]
gyp: ../../builds/gyp/project.gyp not found (cwd: /home/chigozirim/Downloads/temp/czmq-4.2.0/bindings/nodejs) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/chigozirim/Downloads/temp/czmq-4.2.0/bindings/nodejs/node_modules/node-ninja/lib/configure.js:301:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.2.8-arch1-1-ARCH
gyp ERR! command "/home/chigozirim/.nvm/versions/node/v10.15.3/bin/node" "/home/chigozirim/Downloads/temp/czmq-4.2.0/bindings/nodejs/node_modules/.bin/node-ninja" "configure"
gyp ERR! cwd /home/chigozirim/Downloads/temp/czmq-4.2.0/bindings/nodejs
gyp ERR! node -v v10.15.3
gyp ERR! node-ninja -v v1.0.2
gyp ERR! not ok
```

**Comment by sappo** [comment]
Okay, thanks for the build output. I'll look into it later today.

As a workaround you can use the lastest master which should be similarly
stable as the last release.

Chigozirim C. <notifications@github.com> schrieb am Sa., 24. Aug. 2019,
04:50:
