### ISSUE TITLE
zpoller_test random crash on windows

### ISSUE THREAD

**Issue by calvin2021y** [zeromq/czmq#2300]
random test error:

```sh
 * zpoller: =================================================================
==4224==ERROR: AddressSanitizer: access-violation on unknown address 0x007ed9b00158 (pc 0x7ff727400f56 bp 0x007ed9aff890 sp 0x007ed9aff850 T0)
==4224==The signal is caused by a READ memory access.
    #0 0x7ff727400f55  (C:\Users\admin\tests_zmq.exe+0x1402c0f55)
    #1 0x7ff7273128d7  (C:\Users\admin\tests_zmq.exe+0x1401d28d7)
    #2 0x7ff7273129f1  (C:\Users\admin\tests_zmq.exe+0x1401d29f1)
    #3 0x7ff727251b21  (C:\Users\admin\tests_zmq.exe+0x140111b21)
    #4 0x7ff72724f653  (C:\Users\admin\tests_zmq.exe+0x14010f653)
    #5 0x7ff727250ae6  (C:\Users\admin\tests_zmq.exe+0x140110ae6)
    #6 0x7ff7271b21b2  (C:\Users\admin\tests_zmq.exe+0x1400721b2)
    #7 0x7ff727141310  (C:\Users\admin\tests_zmq.exe+0x140001310)
    #8 0x7ff727141365  (C:\Users\admin\tests_zmq.exe+0x140001365)
    #9 0x7ffb3ebd7343 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180017343)
    #10 0x7ffb3f4226b0 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x1800526b0)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: access-violation (C:\Users\admin\tests_zmq.exe+0x1402c0f55)
==4224==ABORTING
```

**Comment by calvin2021y** [comment]
one more random windows test error:

```sh
D: 24-08-17 09:43:06 alpha:     API command=STATUS
DAssertion failed: streq (command, "DELIVER"), file ~\czmq\src\zgossip.c, line 708
```

**Comment by sphaero** [comment]
We've seen random crashes before on Windows but we're missing more windows devs who can trace this and provide a fix.
