### ISSUE TITLE
libczmq.so.1: undefined symbol: zdir_list (python binding)

### ISSUE THREAD

**Issue by sphaero** [zeromq/czmq#998]
I'm trying out the python bindings which are generated. As I couldn't find documentation about is I'm just naively trying out:
```
 $ python czmq.py
Traceback (most recent call last):
  File "czmq.py", line 224, in <module>
    lib.zdir_list.restype = zlist_p
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libczmq.so.1: undefined symbol: zdir_list
```
```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from czmq import *
  File "/home/arnaud/src/czmq/bindings/python/czmq.py", line 224, in <module>
    lib.zdir_list.restype = zlist_p
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libczmq.so.1: undefined symbol: zdir_list
```
And with Python3:
```
$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from czmq import *
  File "/home/arnaud/src/czmq/bindings/python/czmq.py", line 110, in <module>
    PyFile_FromFile = pythonapi.PyFile_FromFile
  File "/usr/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python3: undefined symbol: PyFile_FromFile
```
Using libzmq 4.0.5 (Debian Jessie) latest czmq.

**Comment by sphaero** [comment]
K, ldconfig problem. Next stop: 
```
$ python test.py 
.........F
======================================================================
FAIL: test_zsock (__main__.TestCZMQ)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 895, in test_zsock
    self.assertEquals(string_at(data), "ABCDE")
AssertionError: 'ABCDE\x02\\\t' != 'ABCDE'
```

**Comment by sphaero** [comment]
Regarding python3 the error comes from deprecated C api calls:
http://stackoverflow.com/questions/16130268/python-3-replacement-for-pyfile-asfile

**Comment by twhittock** [comment]
Thanks for catching that - pure luck it'd worked before I guess. Ok to close this?

**Comment by twhittock** [comment]
I believe this is resolved.

**Comment by sphaero** [comment]
sure, it could be similar in more places, but we'll catch that when it happens
